source 'https://supermarket.chef.io'

cookbook "resolver", "= 1.3.0"
cookbook "pam", "= 1.0.2"
cookbook "ntp", "= 1.9.0"
cookbook "yum", "= 3.8.2"
cookbook "sysctl", "= 0.7.0"
cookbook "sensu", "= 2.7.0"
cookbook "chef-splunk", "= 1.4.0"
